spring:
  application:
    name: eureka-server 
  config:
#    import: configserver:http://configserver:8071
    import: configserver:http://127.0.0.1:8071
  cloud:
    loadbalancer:
      ribbon:
        enabled: false