spring:
  application:
    name: book-service 
  profiles:
    active: dev
  config:
    import: configserver:http://configserver:8071

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    lab.cloud: DEBUG

#auditevents  , Exposes audit events information for the current application.
#beans  , Displays a complete list of all the Spring beans in your application.
#caches , Exposes available caches.
#conditions , Shows the conditions that were evaluated on configuration and auto-configuration classes and the reasons why they did or did not match.
#configprops  , Displays a collated list of all\u00A0@ConfigurationProperties.
#env  , Exposes properties from Spring\u2019s\u00A0ConfigurableEnvironment.
#flyway , Shows any Flyway database migrations that have been applied.
#health , Shows application health information.
#httptrace  , Displays HTTP trace information (by default, the last 100 HTTP request-response exchanges).
#info , Displays arbitrary application info.
#integrationgraph , Shows the Spring Integration graph.
#loggers  , Shows and modifies the configuration of loggers in the application.
#liquibase  , Shows any Liquibase database migrations that have been applied.
#metrics  , Shows \u2018metrics\u2019 information for the current application.
#mappings , Displays a collated list of all\u00A0@RequestMapping\u00A0paths.
#scheduledtasks , Displays the scheduled tasks in your application.
#sessions , Allows retrieval and deletion of user sessions from a Spring Session-backed session store. Not available when using Spring Session\u2019s support for reactive web applications.
#shutdown , Lets the application be gracefully shutdown.
#threaddump , Performs a thread dump.

#management.endpoints.web.base-path=/
management.endpoints.enabled-by-default: false

management.endpoint.health:
  enabled: true
  show-details: always

management:
  health:
    circuitbreakers:
      enabled: 'true'
    ratelimiters:
      enabled: 'true'

resilience4j.circuitbreaker:
  instances:
    bookService:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
    authorService:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 6
      ringBufferSizeInHalfOpenState: 4
      waitDurationInOpenState: 20s
      failureRateThreshold: 60

resilience4j.ratelimiter:
  instances:
    bookService:
      limitForPeriod: 5
      limitRefreshPeriod: 5000
      timeoutDuration: 1000ms

resilience4j.retry:
  instances:
    retryBookService:
      maxRetryAttempts: 5
      waitDuration: 10000
      retry-exceptions:
        - java.util.concurrent.TimeoutException

resilience4j.bulkhead:
  instances:
    bulkheadBookService:
      maxWaitDuration: 2ms
      maxConcurrentCalls: 20


resilience4j.thread-pool-bulkhead:
  instances:
    bulkheadBookService:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1
      keepAliveDuration: 20ms
